title: Educational Systems Sync
author: MB2012
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I work at a school district and am looking into learning more about how to
  write code for systems to talk to each other.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
